version: '3.8'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
    - 8761:8761
    networks:
      - backend   
  gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
    - 9090:9090
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on: 
      - eureka-server
    networks:
      - backend  
  ms-user:
    container_name: ms-user
    build:
      context: ./ms-user
    ports:
    - 8020:8020
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on: 
      - eureka-server
    networks:
      - backend  
  ms-auth:
    container_name: ms-auth
    build:
      context: ./ms-auth
    ports:
    - 8030:8030
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on: 
      - eureka-server
    networks:
      - backend  
  ms-chatgpt:
    container_name: ms-chatgpt
    build:
      context: ./ms-chatgpt
    ports:
    - 8010:8010
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on: 
      - eureka-server
    networks:
      - backend  
  ms-billing:
    container_name: ms-billing
    build:
      context: ./ms-billing
    ports:
    - 8050:8050
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on: 
      - eureka-server
    networks:
      - backend  
networks:
  backend: